# Generated by Django 5.0.6 on 2024-07-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="information",
            field=models.TextField(default="这个人什么也没有留下~"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_member",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="membership_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
